# Generated by Django 6.0.1 on 2026-04-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "authors",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BorrowTickets",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("borrow_date", models.DateField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "borrow_tickets",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "categories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Publishers",
            fields=[
                ("publisher_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "publishers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("role", models.TextField()),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="books_images/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.authors",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.categories",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.publishers",
                    ),
                ),
            ],
            options={
                "db_table": "books",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BorrowTicketDetails",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "ticket_id",
                        "book_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("is_returned", models.BooleanField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.books"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.borrowtickets",
                    ),
                ),
            ],
            options={
                "db_table": "borrow_ticket_details",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="borrowtickets",
            name="librarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="borrowtickets_librarian_set",
                to="api.users",
            ),
        ),
        migrations.AddField(
            model_name="borrowtickets",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.users",
            ),
        ),
    ]
