# Generated by Django 6.0.1 on 2026-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fines_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
