# Generated by Django 6.0.1 on 2026-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
