# Generated by Django 6.0.1 on 2026-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_books_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
