# Generated by Django 6.0.1 on 2026-05-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_books_created_at_alter_users_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
