# Generated by Django 6.0.1 on 2026-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_books_publication_year_alter_books_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books_images/"),
        ),
    ]
