# Generated by Django 6.0.1 on 2026-05-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_books_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="authors",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="authors_images/"),
        ),
    ]
