# Generated by Django 6.0.1 on 2026-05-18 02:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_authors_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransactions",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IMPORT", "Nhập kho"), ("EXPORT", "Xuất kho")],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.users",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transactions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryTransactionDetails",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.books"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.inventorytransactions",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transaction_details",
                "managed": True,
            },
        ),
    ]
