# Generated by Django 6.0.1 on 2026-05-18 02:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_inventorytransactions_inventorytransactiondetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransactions",
            name="user",
        ),
        migrations.CreateModel(
            name="ExportTickets",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("export_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.users",
                    ),
                ),
            ],
            options={
                "db_table": "export_tickets",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ExportTicketDetails",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.books"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.exporttickets",
                    ),
                ),
            ],
            options={
                "db_table": "export_ticket_details",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ImportTickets",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("import_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.users",
                    ),
                ),
            ],
            options={
                "db_table": "import_tickets",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ImportTicketDetails",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.books"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.importtickets",
                    ),
                ),
            ],
            options={
                "db_table": "import_ticket_details",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="InventoryTransactionDetails",
        ),
        migrations.DeleteModel(
            name="InventoryTransactions",
        ),
    ]
