# Generated by Django 6.0.1 on 2026-05-18 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_inventorytransactions_user_exporttickets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowticketdetails",
            name="quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
