# Generated by Django 6.0.1 on 2026-05-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_borrowticketdetails_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="fines",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.borrowtickets",
            ),
        ),
    ]
