# Generated by Django 6.0.1 on 2026-05-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_fines_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fines",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fines",
                to="api.borrowtickets",
            ),
        ),
    ]
